# Generated by Django 4.0.3 on 2022-04-21 12:54

from django.db import migrations, models
import yolo.models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='confValue',
            field=models.FloatField(default=0.3, validators=[yolo.models.validatorValue]),
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='iouValue',
            field=models.FloatField(default=0.3, validators=[yolo.models.validatorValue]),
        ),
    ]
